// Auto-generated by scripts/calculate-arena-xp.cjs
// samples=250 seed=1337
export const ARENA_XP_REWARDS = {
    "1": {
        "totalXp": 963,
        "finalLevel": 16,
        "pendingLevelUps": 15,
        "xpRemainder": 36,
        "xpToLevel": 235
    },
    "2": {
        "totalXp": 1154,
        "finalLevel": 16,
        "pendingLevelUps": 15,
        "xpRemainder": 227,
        "xpToLevel": 235
    },
    "3": {
        "totalXp": 1052,
        "finalLevel": 16,
        "pendingLevelUps": 15,
        "xpRemainder": 125,
        "xpToLevel": 235
    },
    "4": {
        "totalXp": 1469,
        "finalLevel": 18,
        "pendingLevelUps": 17,
        "xpRemainder": 14,
        "xpToLevel": 366
    },
    "5": {
        "totalXp": 1477,
        "finalLevel": 18,
        "pendingLevelUps": 17,
        "xpRemainder": 22,
        "xpToLevel": 366
    },
    "6": {
        "totalXp": 1535,
        "finalLevel": 18,
        "pendingLevelUps": 17,
        "xpRemainder": 80,
        "xpToLevel": 366
    }
};
