#!/usr/bin/env node
const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, '..', 'dist');
if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir);
}

function parseDotEnv(envPath) {
    if (!fs.existsSync(envPath)) return {};
    const out = {};
    const raw = fs.readFileSync(envPath, 'utf8');
    for (const line of raw.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        const key = trimmed.slice(0, eq).trim();
        let value = trimmed.slice(eq + 1).trim();
        // Strip surrounding quotes
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
        }
        out[key] = value;
    }
    return out;
}

function writeMantaConfig({ debug, playtestUrl, playtestToken }) {
    const cfg = {
        debug: debug === true,
        playtest: {
            url: playtestUrl || '',
            token: playtestToken || ''
        }
    };
    const content = `// Auto-generated by build.cjs — DO NOT COMMIT (dist/ is gitignored)\nwindow.__MANTA_CONFIG__=${JSON.stringify(cfg)};\n`;
    fs.writeFileSync(path.join(distDir, 'manta-config.js'), content, 'utf8');
    console.log(`✓ dist/manta-config.js (DEBUG_MODE=${cfg.debug ? 'true' : 'false'})`);
}

esbuild.buildSync({
    entryPoints: ['js/main.js'],
    bundle: true,
    minify: true,
    outfile: 'dist/bundle.js',
    format: 'esm'
});

const stats = fs.statSync('dist/bundle.js');
console.log(`✓ dist/bundle.js (${Math.round(stats.size / 1024)}KB)`);

// Write runtime config to gitignored dist/ (never touches tracked files)
const env = parseDotEnv(path.join(__dirname, '..', '.env'));
writeMantaConfig({
    debug: String(env.DEBUG_MODE || '').toLowerCase() === 'true',
    playtestUrl: env.PLAYTEST_URL || '',
    playtestToken: env.PLAYTEST_TOKEN || ''
});
